Fix photon field
CRPropa/CRPropa3 pull request #351
Opened 2021-07-22 15:46 UTC by lukasmerten

This PR should fix the issue brought up in #340.

The issue was twofold:
1) Some tables (interaction rates for redshift independent photo pion production on the EBL) were not correctly copied from version 3.1.6 to version 3.1.7.
2) The check for the CMB target photon field (in PhotoPionProduction) was not implemented correctly.

@Leander Schlegel from Ruhr University Bochum did quite some checks to pin down this problem and confirms that the version of this PR yields the same PPP secondaries as version 3.1.6.

2021-07-27 15:21 UTC, rafaelab requested changes

2021-07-29 14:50 UTC, lukasmerten commented on src/module/PhotoPionProduction.cpp
> +		if (fname == "CMB"){
Should be fixed with the latest commit. I was not aware that more than just the CMB comes without any redshift dependence.

2021-07-29 14:51 UTC, lukasmerten commented
@rafaelab: Do you know why the URB_Fixsen11 field is implemented without any tabulated files? Are the files missing or the implementation a relic?

2021-07-29 14:55 UTC, rafaelab commented
> @rafaelab: Do you know why the URB_Fixsen11 field is implemented without any tabulated files? Are the files missing or the implementation a relic?

There should be files for it. But since this field is quite limited in range and only useful for very specific studies, my suggestion would be to remove it since URB_Nitu21 is more up-to-date. There is also the widely-used URB_Protheroe96. 
I am not aware of a single study using URB_Fixsen11.

2021-07-29 15:16 UTC, lukasmerten commented
Ok, I just looked in PhotoPionProduction and PhotoDisintegration, where no Fixsen files are included. Apparently, all other Fixsen files seem to available in the latest data tar-ball. If it is not too much work I would like to add the missing files rather than deleting Fixsen support. Just in case someone is was using it. What do  you think?

2021-07-29 15:30 UTC, rafaelab commented
That's fine, @lukasmerten .
I just realised that these files are missing from CRPropa3-data. I will make a quick PR fixing that now and you can add the files to the latest tarball.

2021-07-29 16:32 UTC, rafaelab commented
@lukasmerten 
I created a PR for CRPropa3-data. Once you create the new tarball, I will merge this pull request.

2021-07-30 15:34 UTC, lukasmerten commented
> That's fine, @lukasmerten .
> I just realised that these files are missing from CRPropa3-data. I will make a quick PR fixing that now and you can add the files to the latest tarball.

Should be ready now. The new tarball is data-2021-07-30.tar.gz, which is used in ed6f904.

2021-07-30 17:05 UTC, rafaelab approved these changes

2021-07-31 14:35 UTC, merged