Targeting
CRPropa/CRPropa3 pull request #378
Opened 2021-11-29 19:15 UTC by avvliet

This pull request adds a targeted emission routine to the sources. The particles are emitted following a von-Mises-Fisher distribution and given a weight so that it is possible to obtain a distribution as if the particles were emitted isotropically. It also adds an example on how to use this targeted emission, including a learning method to obtain optimised parameters for the von-Mises-Fisher parameters.

2021-11-30 14:02 UTC, lukasmerten commented
Hi @avvliet 
In general this looks good to me. 
I'll have a closer look as soon as possible, but the following things came already to my mind:

1. Please add a short comment in the CHANGELOG, so we do not forget this feature in the next release notes.
2. Is the calculation of the rotation parameter  (alpha, delta, etc.) time critical? Since the parameters do not change after a source was initialized, there is no need to recalculate them every time the prepareCandidate method is called.

2021-11-30 14:40 UTC, lukasmerten commented on doc/pages/example_notebooks/targeting/Targeting.ipynb
> +    "Here we will introduce you to the targeting algorithm in CRPropa, which emits particles from their sources using a von-Mises-Fisher distribution instead of an isotropic distribution. After emiss
should be "...get a weight assigned..."

2021-11-30 15:27 UTC, lukasmerten requested changes

2021-12-01 18:35 UTC, avvliet commented
Hi @lukasmerten
Thanks for checking and commenting on this pull request. I've implemented all the points that you mentioned, so please have a look again.

2021-12-02 11:34 UTC, lukasmerten approved these changes

2021-12-02 11:36 UTC, lukasmerten commented
Thanks for the quick improvements. Let's wait for other other comments for one more day. I'll merge it if nothing else comes up.

2021-12-02 21:33 UTC, rafaelab commented
Thanks, @avvliet.
It looks good to me. I think it can already be merged if no one else has comments.

2021-12-03 09:02 UTC, merged