Uniform interface for the turbulence generation
CRPropa/CRPropa3 pull request #388
Opened 2022-02-21 14:46 UTC by LeanderSchlegel

Dear all,

with this pullrequest we want to provide a fix to the issue of the non-uniform spectral index handling, as described in #387.
Analyzing the problem, we made two changes:

First, to solve the problem for the PlaneWaveTurbulence method using SimpleTurbulenceSpectrum that was shown in #387, we effectively removed the "+1" in the exponent in the denominator of the formula of the power spectrum, to be accordant to the Tautz and Dosch 2013 paper, as suggested in the discussion of the issue.

Second, we found that for a uniform handling, it would be good to also change the argument that is given to energySpectrum() in the general case of TurbulenceSpectrum. Instead of giving it k^ = k * l_bendover, we put the multiplication with the bendoverscale inside of the function to have the same argument (just k) as in SimpleTurbulenceSpectrum.

We tested the combinations of the turbulence models (SimpleTurbulenceSpectrum and TurbulenceSpectrum) with the available methods (PlaneWaveTurbulence and gridbased GridTurbulence and SimpleGridTurbulence) and found them working as expected, producing the right spectral behaviour, as shown in the plots below, where the spectrum for s=5/3. is shown reweighted with 11/3. On the left the PlaneWaveMethod is shown and on the right the gridbased methods.

![fixed](https://user-images.githubusercontent.com/32835331/154966391-17f97437-0e65-4918-bfa1-a859bcfdea8f.png)

While testing the FastWaves optimization for the PlaneWaveTurbulence method, we found a minor typo preventing it from being built, that we fixed within this PR.

Thank you in advance,
@JulienDoerner , @LeanderSchlegel,  @antoniusf

2022-03-28 12:28 UTC, antoniusf commented
Hiya,

just a short update from me: I've been unable to work the past few weeks due to wrist problems, but I will hopefully get around to reviewing this soon.

A quick note of confusion from me: Why is my name undersigned on the PR comment? I've not had any part in this PR up until now.

Cheers,
Antonius

2022-03-28 12:48 UTC, LeanderSchlegel commented
Hi,

no problem, I hope it got better! Thanks for reviewing it.
We wanted to credit your analysis tool and suggestion of the missing "+1" in the issue:)

Cheers,
Leander

2022-03-28 13:31 UTC, antoniusf commented
I see, thanks for explaining!

2022-04-28 10:28 UTC, reichherzerp requested changes
Thank @LeanderSchlegel, @JulienDoerner, @antoniusf  for this important fix. I agree that it is problematic that the default spectral index of the PlaneWaveTurbulence doesn't lead to the Kolomorov-like Turbulence, as opposed to what is written in the comments of the TD13 methods in the source code. 

I tested your code and it works as expected and documented in your description. 

My only change request regards an improvement of the documentation: Please cite and specify in `PlaneWaveTurbulence.h` the formula of the power spectrum from the Tautz and Dosch 2013 paper that is now used.

If someone else can confirm this pull request, we should consider merging it quickly given the problems that the problematic definition in the current master may cause at the moment!

2022-04-28 17:58 UTC, antoniusf commented
Hey, just so we're on the same page on this (because in the mess of the past two months I don't think I've ever communicated this publicly) – the current PR doesn't implement the exact fix suggested in #387 (i.e. fixing the spectrum generation in `TurbulenceSpectrum::energySpectrum`), but instead fixes the generated spectrum in PlaneWaveTurbulence, is that correct? If I see this correctly, the resulting spectrum only *mostly* follows the formula from Tautz & Dosch, since it now outputs

<img src="https://render.githubusercontent.com/render/math?math=\frac{k^q}{(1 %2b k^2) ^ { (s %2b q)/2 %2b 1}} \cdot k^2">

which for k >> 1 (or rather k >> l_bendover) is basically the same as TD13's formula

<img src="https://render.githubusercontent.com/render/math?math=\frac{k^q}{(1 %2b k^2) ^ { (s %2b q)/2 }}">

but since they're not exactly equal (and the approximate equality is only valid for large k), I thought it was worth mentioning this.

Also, @LeanderSchlegel, would you mind removing my name from the PR comment? I don't think it's bad that you want to credit me for some tooling I've written a few years ago, but to me it reads as if I've been involved in the PR somehow and I feel like that might be confusing to others too.

I'm sorry for the delays my injury (and general life circumstances) has caused with respect to my response to this issue; but I hope it's still valuable to you.

2022-05-11 09:38 UTC, JulienDoerner commented
hey, 

I corrected the difference @antoniusf reported. Now the correction term is 1 + k^2. 
Therefore it is necessary to introduce a bendoverscale in the simpleTurbulenceSpectrum. In this case I set it to 1000 times the maximal turbulence scale to ensure to be in the limit k^2 >> 1. 
I checked all tests mentioned before and there is no change in the expected behavior.

Additionally I updated the documentation as @reichherzerp requested.

2022-05-11 11:30 UTC, adundovi commented
Hi @JulienDoerner, thank you for the hard work you put in to resolve this issue I unintentionally caused by merging these two approaches of generating turbulence. I'll checkout the PR now locally and run a few tests myself. However, putting a number, 1000, is a bit confusing - I would either like to avoid it or define a constant equals to 1000 which is named according to some idea from where this 1000 comes from.

2022-05-12 06:03 UTC, JulienDoerner commented
Hey @adundovi, 
I introduced a variable for the scaling factor of 1000 and documented the meaning.

2022-05-13 18:39 UTC, antoniusf commented
I haven't tested it, but everything looks good to me too. Thank you so much for your work!

2022-05-15 19:09 UTC, antoniusf approved these changes
~wait was i still set as reviewer somehow? anyway,~

nevermind it was just an old tab that hadn't updated completely

2022-05-16 06:05 UTC, merged