New advection fields
CRPropa/CRPropa3 pull request #441
Opened 2023-10-04 10:25 UTC by sophieaerdker

This PR adds new shock profiles for simulating diffusive shock acceleration to the AdvectionField module. In the 2023 ICRC proceedings the advection field `OneDimensionalAdvectionShock` was used to obtain the time-dependent spectra at a 1D cartesian shock. Additional shock profiles allow for oblique shocks and 1D radial shocks.

2023-10-05 06:05 UTC, JulienDoerner requested changes

2023-10-05 06:05 UTC, JulienDoerner commented on src/advectionField/AdvectionField.cpp
> +			return 2*a/r - 2*b/r * tanh((r-r_sh)/l_sh) - b/l_sh * (1 - tanh((r-r_sh)/l_sh)*tanh((r-r_sh)/l_sh));
you often use the term `tanh((r - r_sh)  /  l_sh)`. I would precalculate it und use it as a variable to speed up the calculation a bit.

2023-10-05 06:05 UTC, JulienDoerner commented on src/advectionField/AdvectionField.cpp
> +	s << "Shock width: " << l_sh / km  << " km, ";
add module name

2023-10-05 06:05 UTC, JulienDoerner commented on src/advectionField/AdvectionField.cpp
> +
whitespace

2023-10-05 06:05 UTC, JulienDoerner commented on src/advectionField/AdvectionField.cpp
> +
whitespace

2023-10-05 06:05 UTC, JulienDoerner commented on src/advectionField/AdvectionField.cpp
> +ObliqueAdvectionShock::ObliqueAdvectionShock(double r_comp, double vx_up, double vy, double x_sh){
space between `) {`

2023-10-05 06:05 UTC, JulienDoerner commented on src/advectionField/AdvectionField.cpp
> +    v.x = a - b*tanh(x/x_sh);
fix indenting

2023-10-05 06:05 UTC, JulienDoerner commented on src/advectionField/AdvectionField.cpp
> +	s << "Shock width: " << x_sh / km  << " km, ";
module name

2023-10-05 06:08 UTC, JulienDoerner commented
The new module has some set-function for the parameters. For consistency also get-functions would be good. 

And for the functionality it would be good if the position of the shocks could also be shifted, to allow more customized simulations.

2023-10-06 11:55 UTC, sophieaerdker commented on include/crpropa/advectionField/AdvectionField.h
> + @brief Advection field in r-direction with shock at r_sh and width l_sh approximated by tanh()
It's called `OneDimensionalCartesianShock` now

2023-10-06 11:59 UTC, sophieaerdker commented on src/advectionField/AdvectionField.cpp
> +	std::stringstream s;
This way, it's consistent with the other advection fields

2023-10-06 12:39 UTC, sophieaerdker commented
I added the get-functions and changed the name of `OneDimensionalAdvectionShock` to `OneDimensionalCartesianShock` to set apart from `OneDimensionalSphericalShock`. 

I think the change of the shock position is not necessary for the 1D cartesian case, since it's only for testing purposes and basically all other (analytical) works have the 1D shock at x=0. You can simply set your environment around it and it's not suitable for more complex scenarios anyways.

2023-10-07 12:26 UTC, JulienDoerner commented on include/crpropa/advectionField/AdvectionField.h
> +	double getCooling() const;
I guess this get-function should be a bool?

2023-10-07 12:26 UTC, JulienDoerner commented on include/crpropa/advectionField/AdvectionField.h
> +	@param vUpstream //upstream velocity
This description is not the same variable name as in the constructer. This may lead to problems with the doxygen generation.

2023-10-07 12:26 UTC, JulienDoerner commented on include/crpropa/advectionField/AdvectionField.h
> +	@param v_phi 	Rotation speed at r_rot
This is not a parameter of this constuctor

2023-10-16 05:23 UTC, JulienDoerner approved these changes

2023-10-16 05:23 UTC, merged