Possible fix for wrong secondary masses of photons and neutrinos
CRPropa/CRPropa3 pull request #484
Opened 2024-04-22 23:27 UTC by LeanderSchlegel

Dear all,

with this PR we try to fix #483. @lukasmerten, @JulienDoerner and me discussed it and introduced a new function particleMass(int id) in ParticleMass.cpp to fix the bug by calling it in setId(int newId) in ParticleState.cpp. It gives all particles other than nuclei or electrons/positrons a zero rest-mass and could possibly be extended for other particles when needed.

2024-04-23 06:40 UTC, JulienDoerner requested changes
The solution looks good to me. 
I have only smaller style comments. 

And maybe we should include a test in the `testCore` part explicitly checking the secondary mass.

2024-04-23 13:43 UTC, lukasmerten approved these changes

2024-04-23 13:44 UTC, lukasmerten commented
Looks good to me. Let's wait for more comments otherwise I will merge in the next days.

2024-04-23 15:31 UTC, LeanderSchlegel commented
Thank you very much for your feedback! 
As suggested by Julien and in discussion with him, I added two small tests in `testCore,` one extending the test of addSecondary to also check their masses and one new test, covering the new function `particleMass(int id)`.

2024-04-24 07:01 UTC, JulienDoerner approved these changes

2024-04-29 14:27 UTC, merged